### PR TITLE
Remove the weird reference

### PR DESCRIPTION
**Pull request by liwii**
## Context
Follow-up PR of #146. 
## Summary

Fix the weird reference in #146.

## How to check behavior
Same as the process in #146.

### CODE REVIEW

**Review by watasuke102 — CHANGES_REQUESTED** [review]
You can remove brackets

```diff
-  wl_list_insert((board->view_list).prev, &self->link);
+  wl_list_insert(board->view_list.prev, &self->link);
```

**Comment by liwii** [comment]
Fixed. Thanks!!

**Review by watasuke102 — APPROVED** [review]
LGTM!

**Comment by Aki-7** [comment]
@liwii You can merge this pull request!

**Pull request merged**
