### PR TITLE
damage

### PR DESCRIPTION
**Pull request by Aki-7**
## Context

Damage is the area of an image buffer that has changed.
By handling damage precisely, we can reduce repainting cost greatly.

## Summary

- [x] use effective / transformed coordinates neatly
- [x] handle cursor damage
- [x] handle view damage

## Leaving Issues

- #122 
implement precise view damage handling. We will do this after merging #108.
- #123
enable to change output scale / transform (at least for behavior checking during development)

## How to check behavior

No visible change is made.

Check behavior by modifying the code.

### Check output scale / transform

1. In `output.c#wlr_output_create`, between `wlr_output_enable` and `if (wlr_output_commit(..) == false) {`, insert 
```c
  wlr_output_set_transform(self->wlr_output, WL_OUTPUT_TRANSFORM_90);
  wlr_output_set_scale(self->wlr_output, 0.5);
```
2. build
3. run `zen-desktop`

You can use the output by rotate it 90 degrees clockwise.

### Check damage

1. Make `view.c@zn_view_damage_whole` empty.
```c
void
zn_view_damage_whole(struct zn_view *self)
{
  UNUSED(self);
}
```
This will stop notifying view's damage.

2. build
3. run `zen-desktop`
4. run some client.
5. move the cursor around.

You can see the client only the part the cursor has passed, which means that only the region cursor has passed is repainted, and rest region of the screen is not repainted.

### CODE REVIEW

**Comment by watasuke102** [comment]
- output scale / transform
  - I tried both, and looks work well.
- damage
  - I tried with `weston-clickdot` and `weston-terminal`, but they alternately rendered the area the cursor has passed and the area all of the view. It switched when the cursor is moved even outside of the view.

**Comment by Aki-7** [comment]
> I tried with weston-clickdot and weston-terminal with -s option, but they alternately rendered the area the cursor has passed and the area all of the view. It switched when the cursor is moved even outside of the view.

It happens when making view.c@zn_view_damage_whole empty, right?

**Comment by watasuke102** [comment]
> It happens when making view.c@zn_view_damage_whole empty

Yes, I added `return` to the top of `zn_view_damage_whole()`.

**Comment by Aki-7** [comment]
Then, I think that's no problem. A function damaging whole output (`wlr_output_damage_whole` or `wlr_output_damage_add_whole`) was called at somewhere in your environment. That could happen.

**Comment by Aki-7** [comment]
conflict resolved

**Review by watasuke102 — APPROVED** [review]
Nice change!

**Pull request merged**
