### PR TITLE
Bg image fix

### PR DESCRIPTION
**Pull request by rtr-dnd**
## Context

The background image set by @liwii at #152 was different from the one we decided to use as the default. 
In addition, there were a few glitches in other bundled images too, such as transparency problem and shapes not aligning properly.

## Summary

I re-exported bg images to fix those problems. File names are either changed or swapped. Now main bg is the one with gradient and white mesh.

### CODE REVIEW

**Review by watasuke102 — CHANGES_REQUESTED** [review]
Background image isn't shown, and following error log is shown:

```
[ERROR] [zen/scene/scene.c:202] Image format not supported
```

This problem will may solve (#159), but for now, please convert image file. ([ref](https://github.com/zigen-project/zen/pull/160#issuecomment-1250618974))

**Comment by rtr-dnd** [comment]
@watasuke102 
Thank you for your review; I was not aware of the problem.
The images are now converted to RGBA files.

**Review by watasuke102 — APPROVED** [review]
Nice change!

**Review by Aki-7 — APPROVED** [review]
```
!!!            !!!!!!!!!!!!    !!!!!!!!!!!!!!!     !!!!!!   !!!!!!       !!! 
!!!            !!!                  !!!           !!! !!!  !!! !!!       !!!
!!!            !!!    !!!!!!        !!!           !!!  !!! !!!  !!!      !!!
!!!            !!!       !!!        !!!          !!!   !!!!!!   !!!
!!!!!!!!!!!!   !!!!!!!!!!!!         !!!          !!!    !!!!!    !!!     !!!
```

**Pull request merged**
